# =========================================================

# Settings
hide_window_decorations      yes
background_opacity           0.5
background                   #1E1E1E
font_size                    15
font_family                  JetBrainsMono NF Bold
cursor_blink_interval        0.5
cursor_stop_blinking_after   1
# =========================================================

# Shortcuts
map ctrl+tab send_text all \x1b[27;5;9~
map ctrl+shift+tab send_text all 1 # \x1b[27;6;9~
# =========================================================

# Settings
update_check_interval   0
clipboard_control write-clipboard write-primary
